<div class="entry">
    <h1 class="title">¿Qué es el Punto Libre?</h1>
    <p class="meta"></p>
    <p>Es una iniciativa de Proyecto GNU de Venezuela para fortalecer las actividades de las comunidades de Software Libre a nivel nacional en espacios públicos donde se brinde especial atención a los usuarios y las usuarias de Canaima GNU/Linux</p>
    <h1 class="title">¿Por qué nace el Punto Libre?</h1>
    <p class="meta"></p>
    <p>En Venezuela desde el 2004 se han venido implementando fórmulas para fomentar el Software Libre en el país. Ejemplo de eso, además del conocido Decreto Presidencial 3390, está  La Gaceta Oficial 39633, Ordenanza 025 en la cual se ordena a la Administración Pública a usar en adelante sólo computadoras con Canaima GNU/Linux.</p>
    <p>Se hace necesaria una estrategia que fortalezca el soporte para usuarias y usuarios de Canaima GNU/Linux de manera de asegurar que una vez usuarios del sistema libre, no deseen regresar a sistemas privativos debido a la falta de atención y soporte.</p>
    <p>Por esta razón que nace el presente proyecto el cual parte desde la comunidad de Software Libre que hace vida en Proyecto GNU de Venezuela y que responde al llamado de ser protagonistas y particípes de la construcción de una nueva patria, esta vez atendiendo a las venezolanas y venezolanos necesitados de apoyo en el uso de las Tecnologías Libres.</p>
    <p>La comunidad de Software Libre tradicionalmente realuza continuas actividades de soporte y atención al usuario y la usuaria, pero lo hacen en sus ratos libres, en algunos lugares cambiantes y casi siempre en ocasión de la celebración de eventos y fechas insignes en el movimiento del Software Libre: Día de la Libertad del Software, Día del Documento Libre, Sede de un Congreso Nacional de Software Libre (CNSL), Lugar de la Feria Latinoamericana de Instalación de Software Libre (FLISOL), Reuniones de Grupos de Usuarios, Celebración de Distribuciones, etc., sin que sea esto una actividad en la cual se pueda basar un eficiente ni oportuno plan de soporte a Canaima GNU/Linux</p>
</div>